### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by dszyfelb** [keroro824/HashingDeepLearning#13]
I have the following issue:

```
/runme Config_amz.csv
new Network
new Layer
new Node array
Illegal instruction (core dumped)
```

I reversed to [2d10d46 ](https://github.com/keroro824/HashingDeepLearning/commit/2d10d46b5f6f1eda5d19f27038a596446fc17cee) and then I was able to run the experiment.

My TPH configuration:

```
hugeadm --pool-list
Size  Minimum  Current  Maximum  Default
2097152     1000     1000     1000        *
1073741824       20       20       20
```
dmesg says
[`7506565.490401] traps: runme[27327] trap invalid opcode ip:5654a0192380 sp:7ffd6a645dd0 error:0 in runme[5654a0188000+1c000]`
CPU:
```
model name      : Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc
 cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3
cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total
cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d

```
OS: Ubuntu 18.04
g++: 7.4.0

Please let me know if more information is needed

**Comment by xman** [comment]
You may try to remove the -mavx512f in the Makefile.
Haswell doesn't support avx512f, hence it'll run into illegal opcode errors.

**Comment by dszyfelb** [comment]
It helped. Thank you for your advice

**Comment by keroro824** [comment]
@xman Thank you so much! @dszyfelb are you able to run the code? Can I close this issue?

**Comment by dszyfelb** [comment]
@keroro824 Yes I was. Please close the issue. Now I am looking for machine with avx512f support.
