### ISSUE TITLE
batch size for Amazon-670K dataset

### ISSUE THREAD

**Issue by hyoo** [keroro824/HashingDeepLearning#3]
in paper, it says, "We chose a batch size of 128 for Delicious-200K dataset and 256 for Amazon-670K dataset".

but in the code,
https://github.com/keroro824/HashingDeepLearning/blob/master/SLIDE/Config_amz.csv#L6

it is still 128. Which one is correct?

**Comment by keroro824** [comment]
The paper is correct. But we did have experiments for different batch sizes.
