### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by kmsquire** [keroro824/HashingDeepLearning#4]
Hi there, I really like this work.  I'd like to try to reimplement it in Julia.  I can use the paper as a reference, and I'd like to use this code as a reference as well, but since there's no license, I'm not sure if I'm allowed to do so.  Can you add a license to make it explicit (one way or another)?  

Assuming you want people to use this code freely, the MIT license is a good choice.  If you want to be more restrictive about how people use the code, then GPL or "Research use only" would be better.  (I apologize if you already know this!).  

Either way, it would be good to be explicit. Thanks!

(I'd submit the same issue in the  RUSH-LAB version of this repo, but issues are not enabled there.)

**Comment by Tharun24** [comment]
Thank you Kevin for the suggestion. We’ll do that shortly.

Regards,
Tharun Medini

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by keroro824** [comment]
@kmsquire We've added MIT License to it. Thanks for reminding us!
