### ISSUE TITLE
Unable to get Amazon-670k in the format needed

### ISSUE THREAD

**Issue by dsmic** [keroro824/HashingDeepLearning#42]
The download link asks for access, but after two days I did not get access.

Other sources of Amazon-670K have different file format, and it is not documented, what file format you need,

thx for any help

**Comment by dsmic** [comment]
I found another source, which seem to be fine.

**Comment by dorafan** [comment]
Could you please share the source? I have the same issues -- cannot get the permission to download SLIDE's dataset

**Comment by dsmic** [comment]
I think I used http://manikvarma.org/downloads/XC/XMLRepository.html : 

https://drive.google.com/file/d/1TLaXCNB_IDtLhk4ycOnyud0PswWAW6hR/edit
